##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-cafe-team/cafe-session-manager
    - aptitude
    - autoconf-archive
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - expect #required for unbuffer
    - gcc
    - git
    - intltool
    - libdbus-glib-1-dev
    - libgl1-mesa-dev
    - libgles2-mesa-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libice-dev
    - libsm-dev
    - libstartup-notification0-dev
    - libsystemd-dev
    - libx11-dev
    - libxau-dev
    - libxext-dev
    - libxrender-dev
    - libxt-dev
    - libxtst-dev
    - make
    - cafe-common
    - xmlto
    - xsltproc

before_scripts:
  - ./html-cppcheck

build_scripts:
  - ./before-build
  - ./make-scanbuild '--enable-compile-warnings=maximum'
  - ./after-build

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20; fi
